### ISSUE TITLE
freeminer 0.4.14.8 and master failed to build with msgpack-c 2.0.0

### ISSUE THREAD

**Issue by willysr** [freeminer/freeminer#277]
Here's the build error message:

```
[  0%] Building CXX object src/CMakeFiles/freeminerserver.dir/contrib/environment.cpp.o
[  1%] Building CXX object src/CMakeFiles/freeminerserver.dir/contrib/fallingsao.cpp.o
[  1%] Building CXX object src/CMakeFiles/freeminerserver.dir/contrib/itemsao.cpp.o
[  1%] Building CXX object src/CMakeFiles/freeminerserver.dir/contrib/l_env.cpp.o
[  1%] Building CXX object src/CMakeFiles/freeminerserver.dir/network/connection.cpp.o
[  2%] Building CXX object src/CMakeFiles/freeminerserver.dir/network/fm_lan.cpp.o
[  2%] Building CXX object src/CMakeFiles/freeminerserver.dir/network/networkpacket.cpp.o
/tmp/SBo/freeminer-0.4.14.8/src/network/networkpacket.cpp: In function ‘bool parse_msgpack_packet(char*, irr::u32, MsgpackPacket*, int*, msgpack::v1::unpacked*)’:
/tmp/SBo/freeminer-0.4.14.8/src/network/networkpacket.cpp:545:38: error: invalid user-defined conversion from ‘msgpack::v1::unpacked* {aka msgpack::v1::object_handle*}’ to ‘msgpack::v1::zone&’ [-fpermissive]
   msgpack::unpack(msg, data, datasize);
                                      ^
In file included from /usr/include/msgpack/v1/zone.hpp:18:0,
                 from /usr/include/msgpack/zone.hpp:15,
                 from /usr/include/msgpack/v1/object_decl.hpp:15,
                 from /usr/include/msgpack/object_decl.hpp:14,
                 from /usr/include/msgpack/object.hpp:13,
                 from /usr/include/msgpack.hpp:10,
                 from /tmp/SBo/freeminer-0.4.14.8/src/network/../msgpack_fix.h:14,
                 from /tmp/SBo/freeminer-0.4.14.8/src/network/networkprotocol.h:31,
                 from /tmp/SBo/freeminer-0.4.14.8/src/network/networkpacket.h:25,
                 from /tmp/SBo/freeminer-0.4.14.8/src/network/networkpacket.cpp:20:
/usr/include/msgpack/v1/detail/cpp11_zone.hpp:226:8: note: candidate is: msgpack::v1::zone::zone(size_t) <near match>
 inline zone::zone(size_t chunk_size) noexcept:m_chunk_size(chunk_size), m_chunk_list(m_chunk_size)
        ^
/usr/include/msgpack/v1/detail/cpp11_zone.hpp:226:8: note:   conversion of argument 1 would be ill-formed:
/tmp/SBo/freeminer-0.4.14.8/src/network/networkpacket.cpp:545:38: error: invalid conversion from ‘msgpack::v1::unpacked* {aka msgpack::v1::object_handle*}’ to ‘size_t {aka long unsigned int}’ [-fpermissive]
   msgpack::unpack(msg, data, datasize);
                                      ^
/tmp/SBo/freeminer-0.4.14.8/src/network/networkpacket.cpp:545:38: error: invalid conversion from ‘msgpack::v1::unpacked* {aka msgpack::v1::object_handle*}’ to ‘size_t {aka long unsigned int}’ [-fpermissive]
In file included from /usr/include/msgpack/v1/zone.hpp:18:0,
                 from /usr/include/msgpack/zone.hpp:15,
                 from /usr/include/msgpack/v1/object_decl.hpp:15,
                 from /usr/include/msgpack/object_decl.hpp:14,
                 from /usr/include/msgpack/object.hpp:13,
                 from /usr/include/msgpack.hpp:10,
                 from /tmp/SBo/freeminer-0.4.14.8/src/network/../msgpack_fix.h:14,
                 from /tmp/SBo/freeminer-0.4.14.8/src/network/networkprotocol.h:31,
                 from /tmp/SBo/freeminer-0.4.14.8/src/network/networkpacket.h:25,
                 from /tmp/SBo/freeminer-0.4.14.8/src/network/networkpacket.cpp:20:
/usr/include/msgpack/v1/detail/cpp11_zone.hpp:226:8: note:   initializing argument 1 of ‘msgpack::v1::zone::zone(size_t)’
 inline zone::zone(size_t chunk_size) noexcept:m_chunk_size(chunk_size), m_chunk_list(m_chunk_size)
        ^
/tmp/SBo/freeminer-0.4.14.8/src/network/networkpacket.cpp:545:38: error: conversion to non-const reference type ‘class msgpack::v1::zone&’ from rvalue of type ‘msgpack::v1::zone’ [-fpermissive]
   msgpack::unpack(msg, data, datasize);
                                      ^
In file included from /usr/include/msgpack/unpack.hpp:16:0,
                 from /usr/include/msgpack.hpp:14,
                 from /tmp/SBo/freeminer-0.4.14.8/src/network/../msgpack_fix.h:14,
                 from /tmp/SBo/freeminer-0.4.14.8/src/network/networkprotocol.h:31,
                 from /tmp/SBo/freeminer-0.4.14.8/src/network/networkpacket.h:25,
                 from /tmp/SBo/freeminer-0.4.14.8/src/network/networkpacket.cpp:20:
/usr/include/msgpack/v2/unpack.hpp:1536:24: note:   initializing argument 1 of ‘msgpack::v2::object msgpack::v2::unpack(msgpack::v1::zone&, const char*, std::size_t, msgpack::v1::unpack_reference_func, void*, const msgpack::v1::unpack_limit&)’
 inline msgpack::object unpack(
                        ^
src/CMakeFiles/freeminerserver.dir/build.make:206: recipe for target 'src/CMakeFiles/freeminerserver.dir/network/networkpacket.cpp.o' failed
make[2]: *** [src/CMakeFiles/freeminerserver.dir/network/networkpacket.cpp.o] Error 1
CMakeFiles/Makefile2:148: recipe for target 'src/CMakeFiles/freeminerserver.dir/all' failed
make[1]: *** [src/CMakeFiles/freeminerserver.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by proller** [comment]
https://github.com/freeminer/freeminer/commit/7ad981638ea568caf0e3495752cb1bc4a3a853dd

**Comment by willysr** [comment]
Thanks, tested and fixed in master
